# Uncomment the next line to define a global platform for your project

platform :ios, '11.0'

use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'yourThing' do

pod 'GoogleMaps'
pod 'GooglePlacePicker'
pod 'GooglePlaces'

end
